# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: alice-web-server
#   namespace: tenant-a
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: alice-web-server
#   template:
#     metadata:
#       labels:
#         app: alice-web-server
#     spec:
#       container:
#         - name: nginx
#           image: nginx:alpine
#           resources:
#             requests:
#               cpu: "100m"     # 0.1 CPU
#               memory: "64Mi"
#             limits:
#               cpu: "500m"
#               memory: "128Mi"