apiVersion: batch/v1
kind: Job
metadata:
  name: cpu-hog
spec:
  completions: 8 
  parallelism: 8
  template:
    metadata:
      labels:
        app: cpu-hog
    spec:
      restartPolicy: Never
      containers:
      - name: stress
        image: polinux/stress
        command: ["stress"]
        args: ["--cpu", "8", "--timeout", "300s"]
        resources:
          requests:
            cpu: "1000m"