# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress-tenant-b
#   namespace: tenant-b
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /bob(/|$)(.*)
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: bob-web-server
#             port:
#               number: 80